
import java.util.Iterator;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JList;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FriendRequest.java
 *
 * Created on 11-30-2011, 09:43:46 PM
 */
/**
 *
 * @author Gary
 */
public class FriendRequest extends javax.swing.JFrame {
    
    Perfil pf = new Perfil();
    Facebook fb = new Facebook();
   
    login lg = new login();
  
    static String am="";
    
    infoBusqueda fi = new infoBusqueda();

       
    /** Creates new form FriendRequest */
    public FriendRequest() {
        initComponents();

         
     String am[]=  fb.soliAmigos(lg.correo);
DefaultListModel modelo = new DefaultListModel();

        try{
            for(int i=0;i<am.length;i++ ){
                
            modelo.add(i,am[i]);
            }
        }
      catch(Exception qq){
          
      }
            
        lista.setModel(modelo);
        
    }
    
    
    

    /** This method is called from within the constructor to
     * initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        rechazar = new javax.swing.JButton();
        aceptar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        rechazo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(480, 460));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel2.setForeground(new java.awt.Color(0, 255, 153));
        jLabel2.setText("Solicitudes de Amistad :)");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 0, 260, 70);

        rechazar.setText("Rechazar");
        rechazar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                rechazarMouseReleased(evt);
            }
        });
        getContentPane().add(rechazar);
        rechazar.setBounds(300, 190, 90, 23);

        aceptar.setText("Aceptar");
        aceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                aceptarMouseReleased(evt);
            }
        });
        getContentPane().add(aceptar);
        aceptar.setBounds(300, 110, 90, 23);

        lista.setBackground(new java.awt.Color(51, 51, 51));
        lista.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lista.setForeground(new java.awt.Color(0, 255, 153));
        lista.setModel(lista.getModel());
        jScrollPane1.setViewportView(lista);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(90, 90, 150, 190);

        jButton1.setText("Mi Perfil");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(180, 350, 120, 23);

        rechazo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/social-network-1.jpg"))); // NOI18N
        rechazo.setText("jLabel1");
        getContentPane().add(rechazo);
        rechazo.setBounds(0, 0, 480, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aceptarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aceptarMouseReleased

          if(lista.getSelectedIndex()>1){
            JOptionPane.showMessageDialog(this, "Seleccione solo un Correo","ERROR",0);
            return;
       
      
       }else{ 
           
         String nom = (String) this.lista.getSelectedValue();
         System.out.println(nom);
           
    if(fb.confirmFriends(lg.correo, nom,true)){
        
        DefaultListModel modelo = (DefaultListModel) lista.getModel();
        int index = lista.getSelectedIndex();
        modelo.remove( index );
        JOptionPane.showMessageDialog(this, "Solicitud Aceptada","!",1);
   
    
        String amm[]=  fb.losAmigos(Perfil.correo);
       DefaultListModel model = new DefaultListModel();
       
     
 JFileChooser fileChooser = new JFileChooser();       
       int result = fileChooser.showOpenDialog(null);  
        if ( result == JFileChooser.APPROVE_OPTION ){            
              am = fileChooser.getSelectedFile().getName();                
                model.addElement(am);                              
            }
//            for(int i=0;i<amm.length;i++ ){
//           model.add(i,amm[i]);
//           }
    
    }else{
        System.out.println("false");
    }
        
       }
          

       

       
      
        
        // TODO add your handling code here:
    }//GEN-LAST:event_aceptarMouseReleased

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased
        
       String amm[]=  fb.losAmigos(lg.correo);
          
       DefaultListModel model = new DefaultListModel();
                   for(int i=0;i<amm.length;i++ ){
                
           model.add(i,amm[i]);
           }
    
        
        dispose();
            pf.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseReleased

    private void rechazarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rechazarMouseReleased

          if(lista.getSelectedIndex()>1){
            JOptionPane.showMessageDialog(this, "Seleccione solo un Correo","ERROR",0);
            return;
       
          }else{ 
           
         String nom = (String) this.lista.getSelectedValue();
      
      if( fb.confirmFriends(lg.correo, nom,false)){
        
        DefaultListModel modelo = (DefaultListModel) lista.getModel();
        int index = lista.getSelectedIndex();
        modelo.remove( index );
          JOptionPane.showMessageDialog(this, "Solicitud Rechazada","!",0);
      
          
            String amm[]=  fb.losAmigos(Perfil.correo);
          
       DefaultListModel model = new DefaultListModel();
                   for(int i=0;i<amm.length;i++ ){
                
           model.add(i,amm[i]);
           }
      }
          }
          
        
       // TODO add your handling code here:
    }//GEN-LAST:event_rechazarMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                
                
   
                new FriendRequest().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lista;
    private javax.swing.JButton rechazar;
    private javax.swing.JLabel rechazo;
    // End of variables declaration//GEN-END:variables
}
