
import javax.swing.DefaultListModel;
import javax.swing.JList;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FriendRequest.java
 *
 * Created on 11-30-2011, 09:43:46 PM
 */
/**
 *
 * @author Gary
 */
public class FriendRequest extends javax.swing.JFrame {
    
    Perfil pf = new Perfil();
    Facebook fb = new Facebook();
    
    
    
   login lg = new login();
        
       String array[]= new String[fb.contAmigos(pf.correo)];
    
       
    /** Creates new form FriendRequest */
    public FriendRequest() {
        initComponents();
    
        
        DefaultListModel modelo = new DefaultListModel();
    String aka []={"aka47","aka2"};
//    fb.arrAmigos(pf.correo);
    for(int i =0; i <aka.length;i++){
        modelo.add(i,aka[i]);
//        System.out.println(aka[i]);         
//        
        lista.setModel(modelo);      
//        
    
    }
    }
    
    
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel2.setForeground(new java.awt.Color(0, 255, 153));
        jLabel2.setText("Solicitudes de Amistad :)");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 0, 260, 70);

        jButton2.setText("Rechazar");
        getContentPane().add(jButton2);
        jButton2.setBounds(250, 190, 90, 23);

        lista.setModel(lista.getModel());
        jScrollPane1.setViewportView(lista);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(60, 100, 150, 190);

        jButton1.setText("Aceptar");
        getContentPane().add(jButton1);
        jButton1.setBounds(250, 110, 71, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/social-network-1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 480, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
   
                new FriendRequest().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lista;
    // End of variables declaration//GEN-END:variables
}
