
import java.io.RandomAccessFile;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * infoBusqueda.java
 *
 * Created on 11-29-2011, 08:58:26 PM
 */
/**
 *
 * @author Gary
 */
public class infoBusqueda extends javax.swing.JFrame {
    /** Creates new form infoBusqueda */
   
     static ArrayList al = new ArrayList();
     
    public infoBusqueda() {
        initComponents();
        
        BuscarAmigos bff = new BuscarAmigos();
        Facebook fb = new Facebook();
        //System.out.println(bff.mail);
        infoCuadro.setText(fb.bPerfil(bff.mail));
       
       
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addbu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        infoCuadro = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 300));
        setResizable(false);
        getContentPane().setLayout(null);

        addbu.setText("Agregar");
        addbu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                addbuMouseReleased(evt);
            }
        });
        getContentPane().add(addbu);
        addbu.setBounds(150, 220, 100, 23);

        infoCuadro.setBackground(new java.awt.Color(51, 51, 51));
        infoCuadro.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 255, 153)));
        infoCuadro.setEditable(false);
        infoCuadro.setFont(new java.awt.Font("Tahoma", 1, 10));
        infoCuadro.setForeground(new java.awt.Color(0, 255, 153));
        infoCuadro.setDisabledTextColor(new java.awt.Color(0, 204, 102));
        infoCuadro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                infoCuadroKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(infoCuadro);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(80, 70, 240, 130);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel2.setForeground(new java.awt.Color(0, 255, 102));
        jLabel2.setText("Resultados de la Busqueda");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 30, 230, 15);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/social-network-1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addbuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addbuMouseReleased

        Facebook fb = new Facebook ();
         Perfil pf = new Perfil();
       BuscarAmigos fbi = new BuscarAmigos();
        
      
        
         
         if(fb.addFriends(pf.correo,fbi.mail)){
//              String  array[]= new String[fb.contAmigos(Perfil.correo)];
            al.add(pf.correo);    
             
             //fb.arrAmigos(fbi.mail);
//    String names []=new String[fb.contAmigos(Perfil.correo)];           
            //this.al.add(pf.correo);
              JOptionPane.showMessageDialog(this, "Solicitud Envianda", "FaceBins", 1);
         }
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_addbuMouseReleased

    private void infoCuadroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_infoCuadroKeyTyped

        
        // TODO add your handling code here:
    }//GEN-LAST:event_infoCuadroKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new infoBusqueda().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbu;
    private javax.swing.JTextPane infoCuadro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
