
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ModificarPerfil.java
 *
 * Created on 12-08-2011, 04:14:52 PM
 */
/**
 *
 * @author Gary
 */
public class ModificarPerfil extends javax.swing.JFrame {

    /** Creates new form ModificarPerfil */
    public ModificarPerfil() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tel = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        actibox = new javax.swing.JComboBox();
        acp = new javax.swing.JButton();
        diabox = new javax.swing.JComboBox();
        mesbox = new javax.swing.JComboBox();
        yearbox = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(450, 450));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel2.setForeground(new java.awt.Color(0, 255, 102));
        jLabel2.setText("Modificar Perfil");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(180, 20, 140, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel3.setForeground(new java.awt.Color(0, 255, 102));
        jLabel3.setText("Telefono");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(160, 90, 80, 15);
        getContentPane().add(tel);
        tel.setBounds(240, 90, 70, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel4.setForeground(new java.awt.Color(0, 255, 102));
        jLabel4.setText("Fecha de Nacimiento");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(160, 110, 140, 50);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel7.setForeground(new java.awt.Color(102, 255, 153));
        jLabel7.setText("Dia            Mes              Año                    ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(170, 150, 300, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel5.setForeground(new java.awt.Color(0, 255, 153));
        jLabel5.setText("Cuenta Activa:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(110, 250, 100, 15);

        actibox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Activada", "Desactivada" }));
        getContentPane().add(actibox);
        actibox.setBounds(240, 250, 70, 20);

        acp.setText("Modificar");
        acp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                acpMouseReleased(evt);
            }
        });
        getContentPane().add(acp);
        acp.setBounds(100, 340, 90, 23);

        diabox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        getContentPane().add(diabox);
        diabox.setBounds(140, 190, 37, 20);

        mesbox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        getContentPane().add(mesbox);
        mesbox.setBounds(230, 190, 37, 20);

        yearbox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1968", "1967", "1966", "1965", "1964", "1963", "1962", "1961", "1960", "1959", "1958", "1957", "1956", "1955", "1954", "1953", "1952", "1951", "1950", "1949", "1948", "1947", "1946", "1945", "1944", "1943", "1942", "1941", "1940", "1939", "1938", "1937", "1936", "1935", "1934", "1933", "1932", "1931", "1930", "1929", "1928", "1927", "1926", "1925", "1924", "1923", "1922", "1921", "1920", "1919", "1918", "1917", "1916", "1915", "1914", "1913", "1912", "1911" }));
        getContentPane().add(yearbox);
        yearbox.setBounds(310, 190, 49, 20);

        jButton1.setText("Regresar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(233, 340, 100, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/social-network-1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 480, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void acpMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acpMouseReleased

        Facebook fb = new Facebook();
        
        String tt =tel.getText();
//         int t = Integer.parseInt(tt);
         String dd = (String) diabox.getSelectedItem();
         String dm = (String) mesbox.getSelectedItem();
         String yd =(String) yearbox.getSelectedItem();
         
         int d =Integer.parseInt(dd);
         int m =Integer.parseInt(dm);
         int y =Integer.parseInt(yd);
                 
        Calendar c = Calendar.getInstance();
          c.set(y,m,d);
         Date date = c.getTime();
         
         String ac= (String) actibox.getSelectedItem();
       
         
         
//         if(!tt.equals("")){
//           int t = Integer.parseInt(tt);
//      
             if(ac.equals("Activada")&&(!tt.equals(""))){
           int t = Integer.parseInt(tt);

       fb.modificarPerfil(Perfil.correo, t, date.getTime());
        dispose();
        Perfil pf = new Perfil();
        pf.setVisible(true);  
        }
           if(ac.equals("Activada")&&(tt.equals(""))){
            JOptionPane.showMessageDialog(this, "Ingrese un numero telefonico");
                     
           }
         
         
         if(ac.equals("Desactivada")){
             
           fb.cerrar(Perfil.correo);
                 if(fb.desactivarCuenta(Perfil.correo)){
                    dispose(); 
                     System.out.println("BORRANDO...");
                    login lg = new login();
                    lg.setVisible(true);
                     
                     
                 }else{
                     System.out.println("FALSO");
                 }
              
             
         }
         
      
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_acpMouseReleased

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased

        Perfil pf = new Perfil();
        
        pf.setVisible(true);
        
        dispose();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ModificarPerfil().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acp;
    private javax.swing.JComboBox actibox;
    private javax.swing.JComboBox diabox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox mesbox;
    private javax.swing.JTextField tel;
    private javax.swing.JComboBox yearbox;
    // End of variables declaration//GEN-END:variables
}
