
import java.util.Calendar;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * perfilAmigo.java
 *
 * Created on 11-30-2011, 08:35:44 PM
 */
/**
 *
 * @author Gary
 */
public class perfilAmigo extends javax.swing.JFrame {

    static String cc="";
    /** Creates new form perfilAmigo */
    public perfilAmigo() {
        initComponents();

                 
        Facebook fb = new Facebook();
        
        
    infoPerfil.setText(fb.iPerfil(cc));
        
         poster.setText(fb.showComment(cc));
      
    
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CuadroFoto = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        infoPerfil = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        post = new javax.swing.JEditorPane();
        poster = new java.awt.TextArea();
        ClickPost = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        CuadroFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/silueta.jpg"))); // NOI18N
        CuadroFoto.setText("cuadrofoto");
        CuadroFoto.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(51, 255, 153)));
        getContentPane().add(CuadroFoto);
        CuadroFoto.setBounds(30, 60, 160, 170);

        infoPerfil.setBackground(new java.awt.Color(102, 102, 102));
        infoPerfil.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(51, 255, 102)));
        infoPerfil.setEditable(false);
        infoPerfil.setForeground(new java.awt.Color(51, 255, 102));
        jScrollPane1.setViewportView(infoPerfil);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 340, 210, 160);

        jScrollPane4.setHorizontalScrollBar(null);

        post.setBackground(new java.awt.Color(153, 153, 153));
        post.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 255, 102)));
        post.setFont(new java.awt.Font("Tahoma", 1, 11));
        post.setForeground(new java.awt.Color(0, 255, 153));
        post.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                postKeyTyped(evt);
            }
        });
        jScrollPane4.setViewportView(post);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(290, 60, 420, 70);

        poster.setBackground(new java.awt.Color(153, 153, 153));
        poster.setCursor(new java.awt.Cursor(java.awt.Cursor.N_RESIZE_CURSOR));
        poster.setEditable(false);
        poster.setFont(new java.awt.Font("Dialog", 1, 12));
        poster.setForeground(new java.awt.Color(0, 255, 153));
        getContentPane().add(poster);
        poster.setBounds(300, 250, 410, 400);

        ClickPost.setText("Post");
        ClickPost.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ClickPostMouseReleased(evt);
            }
        });
        getContentPane().add(ClickPost);
        ClickPost.setBounds(630, 160, 70, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/social-network-1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 2, 900, 740);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void postKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_postKeyTyped
        
        
        
        
        // TODO add your handling code here:
}//GEN-LAST:event_postKeyTyped

    private void ClickPostMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClickPostMouseReleased
        
        
        
        Facebook fb = new Facebook();  
   
        Calendar c = Calendar.getInstance();
    
        String   ff = post.getText()+"\n"+c.getTime()+"\n\n";
        fb.addComment(cc, ff);
        poster.setText(fb.showComment(cc));
        post.setText("");
   
        
    }//GEN-LAST:event_ClickPostMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new perfilAmigo().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClickPost;
    private javax.swing.JLabel CuadroFoto;
    private javax.swing.JTextPane infoPerfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JEditorPane post;
    private java.awt.TextArea poster;
    // End of variables declaration//GEN-END:variables
}
