
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Registro.java
 *
 * Created on 11-21-2011, 09:36:59 PM
 */
/**
 *
 * @author Gary
 */
public class Registro extends javax.swing.JFrame {
  
    
  
  
  Facebook fb = new Facebook();
  Date d = new Date ();
  
  /** Creates new form Registro */
    public Registro() {
        initComponents();
    }
   

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTel = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Sexo = new javax.swing.JComboBox();
        yearBox = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        mesBox = new javax.swing.JComboBox();
        diaBox = new javax.swing.JComboBox();
        OK = new javax.swing.JButton();
        txtpassw = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/social-network-1.jpg"))); // NOI18N
        jLabel12.setText("jLabel12");

        setBackground(new java.awt.Color(255, 204, 102));
        setMinimumSize(new java.awt.Dimension(500, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel1.setForeground(new java.awt.Color(102, 255, 153));
        jLabel1.setText("Nombre");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 70, 80, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel3.setForeground(new java.awt.Color(102, 255, 153));
        jLabel3.setText("Fecha de Nacimiento");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(140, 180, 140, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel6.setForeground(new java.awt.Color(102, 255, 153));
        jLabel6.setText("Telefono");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(80, 340, 53, 15);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel4.setForeground(new java.awt.Color(102, 255, 153));
        jLabel4.setText("Sexo");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 430, 30, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel5.setForeground(new java.awt.Color(102, 255, 153));
        jLabel5.setText("Email");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 300, 31, 15);
        getContentPane().add(txtTel);
        txtTel.setBounds(160, 340, 110, 20);
        getContentPane().add(txtEmail);
        txtEmail.setBounds(160, 300, 110, 20);

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNameKeyTyped(evt);
            }
        });
        getContentPane().add(txtName);
        txtName.setBounds(170, 70, 110, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel7.setForeground(new java.awt.Color(102, 255, 153));
        jLabel7.setText("Dia            Mes              Año                    ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(100, 210, 300, 30);

        Sexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Femenino" }));
        Sexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SexoActionPerformed(evt);
            }
        });
        getContentPane().add(Sexo);
        Sexo.setBounds(180, 430, 110, 20);

        yearBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1968", "1967", "1966", "1965", "1964", "1963", "1962", "1961", "1960", "1959", "1958", "1957", "1956", "1955", "1954", "1953", "1952", "1951", "1950", "1949", "1948", "1947", "1946", "1945", "1944", "1943", "1942", "1941", "1940", "1939", "1938", "1937", "1936", "1935", "1934", "1933", "1932", "1931", "1930", "1929", "1928", "1927", "1926", "1925", "1924", "1923", "1922", "1921", "1920", "1919", "1918", "1917", "1916", "1915", "1914", "1913", "1912", "1911" }));
        yearBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearBoxActionPerformed(evt);
            }
        });
        getContentPane().add(yearBox);
        yearBox.setBounds(240, 250, 90, 20);

        jLabel9.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24));
        jLabel9.setForeground(new java.awt.Color(102, 255, 153));
        jLabel9.setText("REGISTRO");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(160, 10, 170, 40);

        mesBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        mesBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesBoxActionPerformed(evt);
            }
        });
        getContentPane().add(mesBox);
        mesBox.setBounds(160, 250, 60, 20);

        diaBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        diaBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diaBoxActionPerformed(evt);
            }
        });
        getContentPane().add(diaBox);
        diaBox.setBounds(80, 250, 50, 20);

        OK.setText("Aceptar");
        OK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                OKMouseReleased(evt);
            }
        });
        getContentPane().add(OK);
        OK.setBounds(170, 510, 100, 23);
        getContentPane().add(txtpassw);
        txtpassw.setBounds(170, 140, 110, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel10.setForeground(new java.awt.Color(102, 255, 153));
        jLabel10.setText("Contraseña");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(60, 140, 100, 15);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/social-network-1.jpg"))); // NOI18N
        jLabel13.setText("jLabel13");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(0, 10, 490, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void OKMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OKMouseReleased

       
        
        try{
        
        
         String nombre = this.txtName.getText();
         String password = this.txtpassw.getText();
         
       
         
         String sex = (String) this.Sexo.getSelectedItem();
         char x = sex.charAt(0);
        
         Perfil.correo = this.txtEmail.getText();
         int tel = Integer.parseInt( this.txtTel.getText());
         
         
         
         String dia = (String) this.diaBox.getSelectedItem();
         String mes = (String) this.mesBox.getSelectedItem();
         String year = (String) this.yearBox.getSelectedItem();
        
         int a = Integer.parseInt(dia);
          int   b = Integer.parseInt(mes);
          int   y = Integer.parseInt(year);
 
          Calendar c = Calendar.getInstance();
          c.set(y,b,a);
         Date date = c.getTime();
          
         //Perfil.correo=email;
      
  
        if( fb.addUser(nombre,password,x,date.getTime(),Perfil.correo,tel)){
         JOptionPane.showMessageDialog(this, "Se agrego el Usuario con exito", "GUARDADO", 1);
              
       
            }else{
                JOptionPane.showMessageDialog(this, "No se pudo agregar el Usuario","ERROR",0);
                return;
        }
        }catch(Exception e){
            System.out.println(e.getMessage());//JOptionPane.showMessageDialog(this, "Error: "+cualquiera);//+e.getCause(), "ERROR", 0);            
           
            return;
    }
        HomeFeed hf = new HomeFeed();
        this.dispose();
        hf.setVisible(true);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_OKMouseReleased

    private void txtNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyTyped

        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameKeyTyped

    private void SexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SexoActionPerformed

   
        
        // TODO add your handling code here:
    }//GEN-LAST:event_SexoActionPerformed

    private void diaBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diaBoxActionPerformed
       
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_diaBoxActionPerformed

    private void mesBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesBoxActionPerformed
 
        // TODO add your handling code here:
    }//GEN-LAST:event_mesBoxActionPerformed

    private void yearBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearBoxActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_yearBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Registro().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OK;
    private javax.swing.JComboBox Sexo;
    private javax.swing.JComboBox diaBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox mesBox;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtTel;
    private javax.swing.JPasswordField txtpassw;
    private javax.swing.JComboBox yearBox;
    // End of variables declaration//GEN-END:variables
}
